version: '3.8'

services:
  backend:
    build: ./backend
    container_name: followthru_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://followthru:secret@db:5432/followthru_db
    networks:
      - followthru_network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: followthru_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: followthru
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: followthru_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - followthru_network

  frontend:
    build: ./frontend
    container_name: followthru_frontend
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://localhost:8000
    networks:
      - followthru_network
    depends_on:
      - backend

volumes:
  pgdata:

networks:
  followthru_network:
