version: '3.8'

services:
  backend:
    build: ./backend
    container_name: followthru_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: followthru_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: followthru
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: followthru_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: followthru_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pgdata:
